// Was generated by https://app.quicktype.io/?l=ts
export default interface MoviesListResponseData {
    docs: Doc[]
    total: number
    limit: number
    page: number
    pages: number
}

interface Doc {
    externalId: ExternalID
    poster: Poster
    rating: Rating
    votes: Rating
    id: number
    type: string
    name: string
    year: number
    description: string
    movieLength: number
}

interface ExternalID {
    imdb: string
    tmdb: number
}

interface Poster {
    url: string
    previewUrl: string
}

interface Rating {
    kp: number
    imdb: number
    tmdb: number
}
