// Was generated by https://app.quicktype.io/?l=ts
export default interface MovieResponseData {
    externalId: ExternalID
    poster: Poster
    backdrop: Backdrop
    rating: Rating
    votes: Rating
    videos: Videos
    budget: Budget
    fees: Fees
    distributors: Distributors
    premiere: Premiere
    images: Images
    collections: any[]
    updateDates: any[]
    status: string
    movieLength: number
    productionCompanies: ProductionCompany[]
    spokenLanguages: SpokenLanguage[]
    id: number
    type: string
    name: string
    description: string
    slogan: string
    year: number
    facts: any[]
    genres: Country[]
    countries: Country[]
    seasonsInfo: any[]
    persons: Person[]
    lists: any[]
    typeNumber: number
    alternativeName: string
    enName: null
    names: Country[]
    updatedAt: Date
    ratingMpaa: null
    shortDescription: null
    technology: Technology
    ticketsOnSale: boolean
    similarMovies: SimilarMovie[]
    sequelsAndPrequels: any[]
    createDate: Date
}

interface Backdrop {
    url: string
    previewUrl: string
}

interface Budget {
    value: number
    currency: string
}

interface Country {
    name: string
}

interface Distributors {
    distributor: string
    distributorRelease: string
}

interface ExternalID {
    _id: string
    imdb: string
}

interface Fees {
    _id: string
}

interface Images {
    postersCount: number
    backdropsCount: number
    framesCount: number
}

interface Person {
    id: number
    name: string
    enName: string
    photo: string
    enProfession: string
    description: null | string
}

interface Poster {
    _id: string
    url: string
    previewUrl: string
}

interface Premiere {
    country: string
    world: Date
    russia: null
    digital: null
    bluray: null
    dvd: null
}

interface ProductionCompany {
    name: string
    url: string
    previewUrl: string
}

interface Rating {
    _id: string
    kp: number
    imdb: number
    filmCritics: number
    russianFilmCritics: number
    await: number
}

interface SimilarMovie {
    _id: string
    id: number
    name: string
    enName: string
    alternativeName: string
    poster: Poster
}

interface SpokenLanguage {
    name: string
    nameEn: string
}

interface Technology {
    _id: string
    hasImax: boolean
    has3D: boolean
}

interface Videos {
    trailers: Trailer[]
    teasers: any[]
}

interface Trailer {
    _id: string
    url: string
    name: string
    site: string
    size: number
    type: string
}
