enum SvgId {
    FIND = 'FIND',
    KINOPOISK = 'KINOPOISK',
    IMDB = 'IMDB',
    FILM_REEL = 'FILM_REEL',
    PAGINATION_ONE_PAGE_ARROW = 'PAGINATION_ONE_PAGE_ARROW',
    PAGINATION_ALL_PAGE_ARROW = 'PAGINATION_ALL_PAGE_ARROW',
}

export default SvgId
